import type { Block } from "../types/block";
import { BlockType } from "../types/block";

/**
 * Analysis Report: "库存与供应链分析报告-20250410"
 * Generated by AI Chat → "分析当前库存状况和供应链风险"
 *
 * Contains cross-references to:
 *  - sheet-inventory rows (SKU data)
 *  - sheet-suppliers rows (supplier data)
 *  - sheet-crm rows (customer data)
 *  - canvas-supply-alert, canvas-client-visit (existing documents)
 */
export const analysisReportBlocks: Block[] = [
  // ── Title ──
  {
    id: "ar-b1",
    type: BlockType.Header,
    tokens: [["库存与供应链分析报告-20250410"]],
  },
  {
    id: "ar-b1a",
    type: BlockType.Text,
    tokens: [
      ["标签: "],
      ["智能分析", ["c"]],
      [", "],
      ["库存", ["c"]],
      [", "],
      ["供应链风险", ["c"]],
      [" | 生成时间: 2026-04-10 09:30 | 生成方式: AI Agent 自动分析"],
    ],
  },
  {
    id: "ar-b1b",
    type: BlockType.Callout,
    tokens: [
      [
        "🤖 本报告由 AI Agent 基于当前库存表、供应商表、客户档案表和订单流水表的实时数据自动生成。所有数据点均可溯源至原始记录。",
      ],
    ],
    icon: "🤖",
    color: "rgba(221, 235, 255, 0.3)",
  },

  // ── Chapter 1: Overview ──
  {
    id: "ar-b2",
    type: BlockType.SubHeader,
    tokens: [["一、报告概要"]],
  },
  {
    id: "ar-b2a",
    type: BlockType.Text,
    tokens: [
      ["本报告覆盖截至 2026 年 4 月 10 日的全部业务数据，分析范围包括："],
    ],
  },
  {
    id: "ar-b2b",
    type: BlockType.BulletedList,
    tokens: [["库存数据：5 个核心 SKU 的库存水位与安全线对比"]],
  },
  {
    id: "ar-b2c",
    type: BlockType.BulletedList,
    tokens: [["供应商数据：3 家核心供应商的交期与产能评估"]],
  },
  {
    id: "ar-b2d",
    type: BlockType.BulletedList,
    tokens: [["客户数据：4 家 B2B 客户的需求趋势与信用状况"]],
  },
  {
    id: "ar-b2e",
    type: BlockType.BulletedList,
    tokens: [["订单数据：近期 5 笔订单的履约状态分析"]],
  },

  // ── Chapter 2: Inventory Analysis ──
  {
    id: "ar-b3",
    type: BlockType.SubHeader,
    tokens: [["二、库存状况分析"]],
  },
  {
    id: "ar-b3a",
    type: BlockType.Text,
    tokens: [["基于全局 SKU 与动态库存表的实时数据，当前库存状况如下："]],
  },
  {
    id: "ar-b3b",
    type: BlockType.SubSubHeader,
    tokens: [["🔴 库存严重不足"]],
  },
  {
    id: "ar-b3c",
    type: BlockType.Text,
    tokens: [
      ["@经典款陶瓷马克杯", [["ref", "sheet-inventory", "sheet", "row-mug01"]]],
      [" — 当前库存 "],
      ["200 只", ["b"]],
      ["，安全库存线 500 只，缺口 "],
      ["300 只（60%）", ["b"]],
      ["。该 SKU 为公司销量最高的核心产品，当前库存仅能支撑约 "],
      ["1.5 周", ["b"]],
      [" 的正常出货。"],
    ],
  },
  {
    id: "ar-b3d",
    type: BlockType.Callout,
    tokens: [
      [
        "⚠️ 紧急：经典款陶瓷马克杯库存已低于安全线 60%，且主力供应商景德镇宏图陶瓷交期不稳定（详见供应链风险章节）。建议立即启动紧急补货流程。",
      ],
    ],
    icon: "⚠️",
    color: "rgba(255, 226, 221, 0.3)",
  },
  {
    id: "ar-b3e",
    type: BlockType.SubSubHeader,
    tokens: [["🟢 库存充足"]],
  },
  {
    id: "ar-b3f",
    type: BlockType.BulletedList,
    tokens: [
      ["@简约白瓷餐盘", [["ref", "sheet-inventory", "sheet", "row-plate01"]]],
      [" — 当前库存 800 只，安全线 300 只，"],
      ["充足（267%）", ["b"]],
    ],
  },
  {
    id: "ar-b3g",
    type: BlockType.BulletedList,
    tokens: [
      ["@日式陶瓷碗", [["ref", "sheet-inventory", "sheet", "row-bowl01"]]],
      [" — 当前库存 650 只，安全线 200 只，"],
      ["充足（325%）", ["b"]],
    ],
  },
  {
    id: "ar-b3h",
    type: BlockType.SubSubHeader,
    tokens: [["🟡 需关注"]],
  },
  {
    id: "ar-b3i",
    type: BlockType.BulletedList,
    tokens: [
      ["@双层隔热玻璃杯", [["ref", "sheet-inventory", "sheet", "row-cup01"]]],
      [
        " — 当前库存 450 只，安全线 300 只，暂时安全但需关注。S 级客户老王已表达采购意向，预计 Q2 需求增长。",
      ],
    ],
  },
  {
    id: "ar-b3j",
    type: BlockType.BulletedList,
    tokens: [
      [
        "@手冲咖啡壶套装",
        [["ref", "sheet-inventory", "sheet", "row-kettle01"]],
      ],
      [" — 当前库存 120 套，安全线 80 套，暂时安全。高端产品线，周转较慢。"],
    ],
  },

  // ── Chapter 3: Supply Chain Risk ──
  {
    id: "ar-b4",
    type: BlockType.SubHeader,
    tokens: [["三、供应链风险评估"]],
  },
  {
    id: "ar-b4a",
    type: BlockType.Text,
    tokens: [
      ["根据 "],
      [
        "@Q2 华东区供应链异常预警报告",
        [["ref", "canvas-supply-alert", "canvas"]],
      ],
      [" 及供应商产能评估表数据，当前供应链存在以下风险："],
    ],
  },
  {
    id: "ar-b4b",
    type: BlockType.SubSubHeader,
    tokens: [["高风险供应商"]],
  },
  {
    id: "ar-b4c",
    type: BlockType.Text,
    tokens: [
      ["@景德镇宏图陶瓷", [["ref", "sheet-suppliers", "sheet", "row-jdz"]]],
      [
        "（陶瓷类主力供应商）：受华东地区环保政策收紧影响，燃煤窑炉面临停产整改。原定 3 天的 Lead Time 实际可能拉长至 ",
      ],
      ["5-7 天", ["b"]],
      ["。影响品类：经典款陶瓷马克杯、简约白瓷餐盘、日式陶瓷碗。"],
    ],
  },
  {
    id: "ar-b4d",
    type: BlockType.Callout,
    tokens: [
      [
        "🔥 风险等级：高。景德镇宏图陶瓷供应了公司 70% 的陶瓷类 SKU，一旦停产将严重影响核心产品供应。预计影响周期 2-3 个月。",
      ],
    ],
    icon: "🔥",
    color: "rgba(255, 226, 221, 0.3)",
  },
  {
    id: "ar-b4e",
    type: BlockType.SubSubHeader,
    tokens: [["低风险供应商"]],
  },
  {
    id: "ar-b4f",
    type: BlockType.BulletedList,
    tokens: [
      ["@河北晶透玻璃", [["ref", "sheet-suppliers", "sheet", "row-hb"]]],
      [
        "（玻璃类供应商）：产能稳定，交期正常（2 天）。可作为陶瓷类 SKU 的替代方案供应商。",
      ],
    ],
  },
  {
    id: "ar-b4g",
    type: BlockType.BulletedList,
    tokens: [
      ["@德化白瓷工坊", [["ref", "sheet-suppliers", "sheet", "row-dehua"]]],
      [
        "（备选陶瓷供应商）：使用天然气窑炉，不受环保政策影响。正在推进准入流程，预计 2 周内完成。",
      ],
    ],
  },

  // ── Chapter 4: Customer Demand Impact ──
  {
    id: "ar-b5",
    type: BlockType.SubHeader,
    tokens: [["四、客户需求影响分析"]],
  },
  {
    id: "ar-b5a",
    type: BlockType.Text,
    tokens: [
      ["基于 B2B 客户档案与授信表及 "],
      [
        "@重点客户 Q1 拜访与授信调整纪要",
        [["ref", "canvas-client-visit", "canvas"]],
      ],
      ["，当前客户需求对库存的影响评估如下："],
    ],
  },
  {
    id: "ar-b5b",
    type: BlockType.SubSubHeader,
    tokens: [["S 级客户 — 高优先级"]],
  },
  {
    id: "ar-b5c",
    type: BlockType.Text,
    tokens: [
      [
        "@华中区-星巴克加盟商-老王",
        [["ref", "sheet-crm", "sheet", "row-laowang"]],
      ],
      ["：Q2 预计马克杯采购量激增 "],
      ["300%", ["b"]],
      [
        "（约 3,600 只），同时新增双层隔热玻璃杯品类需求（500-800 只）。当前马克杯库存仅 200 只，",
      ],
      ["远不能满足需求", ["b"]],
      ["。"],
    ],
  },
  {
    id: "ar-b5d",
    type: BlockType.SubSubHeader,
    tokens: [["A 级客户 — 需关注"]],
  },
  {
    id: "ar-b5e",
    type: BlockType.BulletedList,
    tokens: [["华东区-瑞幸代理商-老张：月均采购量稳定，暂无异常波动"]],
  },
  {
    id: "ar-b5f",
    type: BlockType.BulletedList,
    tokens: [
      [
        "西南区-Manner代理商-老孙：Q1 有客诉记录（釉面气泡），需持续关注质量管控",
      ],
    ],
  },
  {
    id: "ar-b5g",
    type: BlockType.SubSubHeader,
    tokens: [["B 级客户 — 观察期"]],
  },
  {
    id: "ar-b5h",
    type: BlockType.BulletedList,
    tokens: [
      [
        "华南区-喜茶供应商-老李：新客户，Q2 预计追加日式陶瓷碗采购，当前库存充足可满足",
      ],
    ],
  },

  // ── Chapter 5: Recommendations ──
  {
    id: "ar-b6",
    type: BlockType.SubHeader,
    tokens: [["五、业务建议与行动项"]],
  },
  {
    id: "ar-b6a",
    type: BlockType.Callout,
    tokens: [
      [
        "📋 综合以上分析，当前最紧迫的问题是：经典款陶瓷马克杯库存严重不足 + 主力供应商交期不稳定 + S 级客户需求激增。需立即采取行动。",
      ],
    ],
    icon: "📋",
    color: "rgba(255, 243, 224, 0.5)",
  },
  {
    id: "ar-b6b",
    type: BlockType.SubSubHeader,
    tokens: [["紧急行动（本周内）"]],
  },
  {
    id: "ar-b6c",
    type: BlockType.ToDo,
    tokens: [["对经典款陶瓷马克杯实施限量供应，优先保障 S 级客户老王的订单"]],
    checked: false,
  },
  {
    id: "ar-b6d",
    type: BlockType.ToDo,
    tokens: [["联系景德镇宏图陶瓷确认窑炉改造进度和预计恢复时间"]],
    checked: false,
  },
  {
    id: "ar-b6e",
    type: BlockType.ToDo,
    tokens: [["加速德化白瓷工坊的供应商准入流程，作为备选方案"]],
    checked: false,
  },
  {
    id: "ar-b6f",
    type: BlockType.SubSubHeader,
    tokens: [["短期行动（两周内）"]],
  },
  {
    id: "ar-b6g",
    type: BlockType.ToDo,
    tokens: [["与河北晶透玻璃沟通，评估玻璃替代方案的可行性和产能"]],
    checked: false,
  },
  {
    id: "ar-b6h",
    type: BlockType.ToDo,
    tokens: [["通知所有 B2B 客户可能的交期延长，提前管理预期"]],
    checked: false,
  },
  {
    id: "ar-b6i",
    type: BlockType.ToDo,
    tokens: [["为老王的 Q2 大单预留库存空间，协调仓储部门备货"]],
    checked: false,
  },
  {
    id: "ar-b6j",
    type: BlockType.SubSubHeader,
    tokens: [["中期规划（Q2 内）"]],
  },
  {
    id: "ar-b6k",
    type: BlockType.ToDo,
    tokens: [["建立多供应商并行供应机制，降低单一供应商依赖风险"]],
    checked: false,
  },
  {
    id: "ar-b6l",
    type: BlockType.ToDo,
    tokens: [["评估老王授信额度提升至 80 万的申请（待 Q2 首月回款确认）"]],
    checked: false,
  },
  {
    id: "ar-b6m",
    type: BlockType.ToDo,
    tokens: [["推进腾讯集团等新客户的试采合作，拓展客户基盘"]],
    checked: false,
  },
  {
    id: "ar-b7",
    type: BlockType.Divider,
    tokens: [],
  },
  {
    id: "ar-b8",
    type: BlockType.SubHeader,
    tokens: [["附：关联数据源"]],
  },
  {
    id: "ar-b8a",
    type: BlockType.EmbedSheet,
    tokens: [["全局 SKU 与动态库存表"]],
    sheetId: "sheet-inventory",
  },
  {
    id: "ar-b8b",
    type: BlockType.EmbedSheet,
    tokens: [["供应商与产能评估表"]],
    sheetId: "sheet-suppliers",
  },
];
